[package]
name = "bfck"
version = "0.1.0"
authors = ["Slava Zipp <zipp.pnl@gmail.com>"]
repository = "https://github.com/zippunov/bfck.git"
homepage = "https://github.com/zippunov/bfck.git"
readme = "README.md"

[lib]
name = "bfck"
crate-type = ["lib"]

[dependencies]
